### ISSUE TITLE
is this open source?

### ISSUE THREAD

**Issue by adbenitez** [rndD/js13k_2024#1]
hi, is this project open source? there is no LICENSE file. I would like to port it to [Webxdc](https://webxdc.org/) or maybe are you interested in supporting webxdc yourself? that would be awesome

(webxdc are sandboxed mini-games shared in a chat, basically a zip attachment with an index.html and other files inside)

**Comment by rndD** [comment]
Hi mate, thanks for asking. 

Right now, I don't have any plans on porting the game to Webxdc.
I added `LICENSE` file so you can use the source code accordingly to CC BY-NC 4.0.
